on: 
    workflow_dispatch:
name: build_deploy_workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }}

        - name: 'Deploy backend to Azure Container Instances'
          run: |
            az container create \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --name aci-uc-b11-two \
              --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/backend:${{ github.sha }} \
              --cpu 1 --memory 2 \
              --location east us \
              --vnet ${{ secrets.VNET_NAME }} \
              --subnet ${{ secrets.SUBNET_NAME }} \
              --ports 80 \
              --tags owner=Divya purpose=usecase Ticket ID=11222 Domain=Cloud&DevOps \
              --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
              --registry-username ${{ secrets.REGISTRY_USERNAME }} \
              --registry-password ${{ secrets.REGISTRY_PASSWORD }}
              
